# --- Base de données PostgreSQL ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=scanner_user
quarkus.datasource.password=change-me
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/appsec_scanner
quarkus.hibernate-orm.database.generation=update

# --- JWT (SmallRye JWT) ---
# Générer une paire de clés RSA : openssl genrsa -out privateKey.pem 2048
#                                  openssl rsa -in privateKey.pem -pubout -out publicKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=mini-appsec-scanner
smallrye.jwt.sign.key.location=privateKey.pem

# --- Scheduler ---
quarkus.scheduler.enabled=true

# --- CORS (pour le dashboard front en dev) ---
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/

# --- Logs ---
quarkus.log.level=INFO

quarkus.http.port=8082
